### ISSUE TITLE
Initial issue - landing page

### ISSUE THREAD

**Issue by DanSchrader** [DanSchrader/capstone-project#1]
## Value Preposition

**As a ** user
**I need** to see a landing page with a specific content
**to be able to** imagine, what the app is about

## Description

<img width="400" src="https://github.com/DanSchrader/capstone-project/blob/6b81bd6057b3185cc56e233ad5e55e94a3d3df21/issues/issue-01-landing-page.svg" alt="issue-01">

## Acceptance Criteria

- [ ] landing page shows a header with logo and title
- [ ] landing page shows a graph and text information about the current value of Raptoreum
- [ ] the graph and text information is updated live

## Tasks

- [ ] create feature branch
- [ ] create component header with logo and title
- [ ] fetch data from (Coinbase) api
- [ ] render data in component ValueGraph
- [ ] render data in component ValueText
- [ ] add simple styling to components
