### ISSUE TITLE
news-page

### ISSUE THREAD

**Issue by DanSchrader** [DanSchrader/capstone-project#10]
## Value Preposition

**As a** user
**I need** to see a news page with a list of news
**to be able to** stay informed about recent changes around Raptoreum

## Description

![doc-page](https://user-images.githubusercontent.com/98756494/163364062-efd50f7f-dfbf-477a-829e-80be65117035.png)

## Acceptance Criteria

- [ ] doc-page shows a list of news articles 
- [ ] the news articles are in chronological order
- [ ] chronological order is top-down from the most recent article

## Tasks

- [ ] create feature branch news-page
- [ ] create a link-button on dashboard page (Mehr anzeigen...) to news page
- [ ] create data-array with content of news and date-id 
- [ ] map through the data-array on the dashboard page
- [ ] map through the data-array on the news page
- [ ] render the articles top-down in chronological order
- [ ] add first styling to the page
