### ISSUE TITLE
mining-tut-page

### ISSUE THREAD

**Issue by DanSchrader** [DanSchrader/capstone-project#12]
## Value Preposition

**As a** user
**I need** to see a mining tutorial page with a step by step tutorial article
**to be able to** follow these steps on my system

## Description

![mining-tut-page](https://user-images.githubusercontent.com/98756494/163797698-54bff52b-cba4-4c1c-88d0-7e4aed58f4cd.png)

## Acceptance Criteria

- [ ] mining-tut page shows a headline
- [ ] mining-tut page shows an article with a step by step tutorial
- [ ] images used in the tutorial should grow on click and close on close-button (x)

## Tasks

- [ ] create feature branch mining-tut
- [ ] create a headline
- [ ] create an article with a tutorial
- [ ] each step shows an image to visualize, which has to be embedded in the text
- [ ] image has to scale full screen on click on it
- [ ] full screen image has a close-button (x)
- [ ] close-button (x) closes full screen view of image and returns to the article
