### ISSUE TITLE
Raptoreum description

### ISSUE THREAD

**Issue by DanSchrader** [DanSchrader/capstone-project#14]
## Value Preposition

**As a** user
**I need** to see a button with the content "Was ist Raptoreum?"
**to be able to** see an explanation about Raptoreum.

## Description

The button is part of a list of buttons and when it's clicked an animated answer layer slides in from the left.

## Acceptance Criteria

- [] button has the content "Was ist Raptoreum?"
- [] it is part of a list of buttons on explanation page
- [] when it's clicked, an explanation layer slides in from the left

## Tasks

- [ ] create feature branch raptoreum-explanation
- [ ] create a button with the content "Was ist Raptoreum"
- [ ] that button will be part of the list of buttons on the explanation page
