### ISSUE TITLE
explanation data update

### ISSUE THREAD

**Issue by DanSchrader** [DanSchrader/capstone-project#15]
## Value Preposition

**As a** user
**I need** to see an explanation layer sliding in
**to be able to** get a description of Raptoreum.

## Description

The explanation layer needs content, which has to be updated in the explanation data.

## Acceptance Criteria

- [x] explanation layer needs a headline
- [x] explanation layer needs text

## Tasks

- [x] create feature branch explanation-update
- [x] update data in explanation data 
- [x] the new data will be a description of Raptoreum
