### ISSUE TITLE
Loading-graphic

### ISSUE THREAD

**Issue by DanSchrader** [DanSchrader/capstone-project#17]
## Value Preposition

**As a** user
**I need** to see a placeholder for the fetched api data
**to be able to** understand, that I have to wait for the information to render.

## Description

![loading-placeholder](https://user-images.githubusercontent.com/98756494/164406246-cad9485c-72c3-4454-b233-9caac4e0d867.png)

## Acceptance Criteria

- [ ] dashboard page shows a logo instead of text "is loading", while waiting for the data fetch from api
- [ ] the logo has an animated circle around it

## Tasks

- [ ] create feature branch loading-graphic
- [ ] replace one placeholder text with a Raptoreum logo and center it
- [ ] replace the other placeholder with an animated colored circle
