### ISSUE TITLE
main-content-preview

### ISSUE THREAD

**Issue by DanSchrader** [DanSchrader/capstone-project#2]
## Value Preposition

**As a** user
**I need** to see a graph and text information in the main
**to be able to** get a preview of Raptoreum's value

## Description

![graph-and-textinfo](https://user-images.githubusercontent.com/98756494/159736522-b13baa6a-136f-4858-b840-3a7bf3c1fac1.png)

## Acceptance Criteria

- [ ] root page shows a graph and text information about the current value of Raptoreum

## Tasks

- [ ] create feature branch
- [ ] placeholder image for graph
- [ ] placeholder text for current value
- [ ] add simple styling to components
