### ISSUE TITLE
responsive-corrections

### ISSUE THREAD

**Issue by DanSchrader** [DanSchrader/capstone-project#20]
## Value Preposition

**As a** user
**I need** to see a responsive design of the app
**to be able to** use it on different devices.

## Description

The design of the app needs to fit desktop and mobile view.

## Acceptance Criteria

- [ ] the app's design pleases in mobile view
- [ ] the apps's design pleases also in desktop view

## Tasks

- [ ] create feature branch corrections
- [ ] add media queries to relevant components for mobile view and 960px+ desktop view
- [ ] style the media queries different to fit both mobile and desktop view
