### ISSUE TITLE
fetch-data-from-api

### ISSUE THREAD

**Issue by DanSchrader** [DanSchrader/capstone-project#3]
## Value Preposition

**As a** user
**I need** to see live updated content in the graph and the text 
**to be able to** get updated information on Raptoreum's current value

## Description

![fetch-data-from-api](https://user-images.githubusercontent.com/98756494/159738991-6bc15ed3-2bee-49e4-8147-3fdcf5b287a9.png)

## Acceptance Criteria

- [x] rendered graph is updated live
- [x] rendered text information is updated live

## Tasks

- [x] create feature branch
- [x] fetch data from (Coinbase) api
- [x] render data in component ValueGraph
- [x] render data in component ValueText
