### ISSUE TITLE
navigation-burger-menu

### ISSUE THREAD

**Issue by DanSchrader** [DanSchrader/capstone-project#4]
## Value Preposition

**As a** user
**I need** to click a navigation button
**to be able to** see a dropdown navigation menu

## Description

![navigation-burger-menu](https://user-images.githubusercontent.com/98756494/159950482-1327cb17-0274-4a38-a3b7-69217866886f.png)

## Acceptance Criteria

- [ ] burger menu button is clickable
- [ ] when clicked, it shows a dropdown menu with navigation links to all existing pages

## Tasks

- [ ] create feature branch
- [ ] create component navigation
- [ ] add a burger menu button with toggle function to component navigation
- [ ] add a dropdown menu to component navigation, that shows NavLinks
- [ ] add react router
- [ ] add useNavigate

**Comment by PReichetanz** [comment]
Does "all existing pages" (i.e. "Dashboard" and "Was ist Raptoreum?", I think) look the same or is the menu button in a different place? You should be more specific here.
