### ISSUE TITLE
doc-page

### ISSUE THREAD

**Issue by DanSchrader** [DanSchrader/capstone-project#5]
## Value Preposition

**As a** user
**I need** to see a documentation page with a toggleable button
**to be able to** show and hide cards, that contain information on subjects I'm interested in

## Description

![doc-page](https://user-images.githubusercontent.com/98756494/159958680-04fab9d4-316c-42d4-9aa0-18b468b8a897.png)

## Acceptance Criteria

- [ ] doc-page has a clickable button "Was ist Raptoreum?"
- [ ] clickable button toggles the visibility of an info card with a description of Raptoreum

## Tasks

- [ ] create feature branch doc-page
- [ ] create component ButtonRaptoreum with the text "Was ist Raptoreum?"
- [ ] create textbox with information on Raptoreum
- [ ] make the button toggleable, showing and hiding the textbox on toggle
- [ ] add first styling to the page
